<?php
/**
 * This file was automatically generated by Genesis Pro Tools.
 *
 * @package    Genesis Pro Tools
 * @author     Calvin Koepke <hello@calvinkoepke.com>
 * @version    1.0.0
 * @link       https://genesisprotools.com
 * @since      1.0.0
 */

/**
 * Autoload packages.
 *
 * @since 1.0.0
 */
require_once( get_stylesheet_directory() . '/vendor/autoload.php' );

/**
 * Instantiate Genesis Pro Tools Core to enable the development workflow.
 *
 * @since 1.0.0
 */
GenesisProTools::init();