<?php
/**
 * This file was automatically generated by Genesis Pro Tools.
 *
 * @package    Genesis Pro Tools
 * @author     Calvin Koepke <hello@calvinkoepke.com>
 * @version    1.0.0
 * @link       https://genesisprotools.com
 * @since      1.0.0
 */

// Mobile viewport tag.
add_theme_support( 'genesis-responsive-viewport' );

// HTML5 markup.
add_theme_support( 'html5', array(
	'search-form',
	'comment-form',
	'comment-list',
	'gallery',
	'caption',
) );

// Accessibility features.
add_theme_support( 'genesis-accessibility', array(
	'skip-links',
	'search-form',
	'drop-down-menu',
	'headings',
) );
